steps:
# Install dependencies
- name: "gcr.io/cloud-builders/npm"
  args: ["install"]
# Run test
- name: "gcr.io/cloud-builders/npm"
  args: ["run", "test"]

- id: build-image
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash 
  args: ["-c" ,"docker build --tag gcr.io/film-app-380914/github.com/tunji93/codematic-test-final:$SHORT_SHA ."]

- id: push
  name: 'gcr.io/cloud-builders/docker'
  
  args: ["push","gcr.io/film-app-380914/github.com/tunji93/codematic-test-final:$SHORT_SHA"]

- id: deploy
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', '$_GCP_SERVICE_NAME', '--image', "gcr.io/film-app-380914/github.com/tunji93/codematic-test-final:$SHORT_SHA", "--region", "us-central1"]


